### ISSUE TITLE
No support for animations? 

### ISSUE THREAD

**Issue by Thepiggy** [jaseg/lolcat#12]
The more popular Ruby lolcat has support for animations? Seeing as this is the objectively superior version I think it should include all the features of the aforementioned.

**Comment by jaseg** [comment]
Help me out here, what kind of animation do you mean? Like, scrolling the colors with the text being static?

**Comment by dosentmatter** [comment]
I think he's talking about the `--animate, -a` flag of [lolcat-rb](https://github.com/busyloop/lolcat)
![animate](https://user-images.githubusercontent.com/5732253/33599830-362316b2-d95c-11e7-8b34-8137416a6acf.gif)

**Comment by jaseg** [comment]
Thank you for the clarification. A sane implementation of this would require the addition of a full-blown pager, which
1. is non-trivial
2. goes counter the unix philosophy
3. would make this more of a lol-more than lol-cat

Thus I'll close this as "wontfix". Sometimes the absence of a feature is a feature, too.

If you desperately need this behavior I'd suggest a switch to add a time-dependent offset to the color index and running the resulting binary with ```watch```.
