### ISSUE TITLE
Error compiling with clang

### ISSUE THREAD

**Issue by Janfel** [jaseg/lolcat#14]
```
OS: Manjaro Linux 17.1.11
Compiler: clang version 6.0.1
AUR Helper: yay v8.922
```
When installing with
`$ yay -S c-lolcat`
during the `build()` phase, this error occurs:
```
/usr/bin/clang -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -o lolcat lolcat.c
lolcat.c:135:9: error: function definition is not allowed here
        {
        ^
lolcat.c:146:37: error: use of undeclared identifier 'helpstr_hack'
            this_file_read_wchar = &helpstr_hack;
                                    ^
2 errors generated.
make: *** [Makefile:14: lolcat] Fehler 1
```
The error does not occur when compiling with gcc using
`$ CC=gcc yay -S c-lolcat`
In this case the output is simply:
```
gcc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -o lolcat lolcat.c
gcc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -o censor censor.c
```

**Comment by dosentmatter** [comment]
I have the same problem with both `gcc` and `clang`. `wint_t helpstr_hack(FILE * _ignored)` is a nested function declaration within the `main()` function. I'm not the best with C, but I can't find any sources that say nested functions are allowed within another function.

It works if I move `wint_t helpstr_hack(FILE * _ignored)` outside of `main()` and put it right before `main()`. I didn't look into the details of what the function does though.

**Comment by jaseg** [comment]
Thank you for reporting this. It's fixed in master now.
