### ISSUE TITLE
Buggy behavior

### ISSUE THREAD

**Issue by lumi-sch** [jaseg/lolcat#20]
- `cava | lolcat` results in a borked terminal and a crashing lolcat.
- (original lolcat doesn't always start with the same color)

**Comment by jaseg** [comment]
> cava | lolcat results in a borked terminal and a crashing lolcat.

cava seems to be a curses application. lolcat and similar tools won't work with curses applications without including a full tmux-style terminal emulator. I don't think that can be done in less than 200loc, thus it is out of scope for this project.

> (original lolcat doesn't always start with the same color)

File bug in original lolcat tracker
