### ISSUE TITLE
Randomly reports "Error reading input file" when printing the same file

### ISSUE THREAD

**Issue by trk9001** [jaseg/lolcat#35]
When printing the same file, lolcat sometimes displays the message `Error reading input file "...": No such file or directory` after correctly printing the file, and sometimes does not. It seems to be random. A screenshot of this occurrence is given below:

![lolcat-error](https://user-images.githubusercontent.com/32555337/102908080-266c7e80-44a1-11eb-967f-7727c6e4d62c.jpg)

### How to reproduce

Repeat printing a file with lolcat a few times, as in the screenshot.

### Output of `lolcat --version`

```
lolcat version 0.1, (c) 2014 jaseg
```

### Package info (on Fedora 33)

```
Name         : lolcat
Version      : 1.0
Release      : 8.fc33
Architecture : x86_64
Size         : 34 k
Source       : lolcat-1.0-8.fc33.src.rpm
Repository   : @System
From repo    : fedora
Summary      : High-performance implementation of a colorful cat
URL          : https://github.com/jaseg/lolcat/
License      : WTFPL
Description  : lolcat is a colorful version of 'cat'. It is faster than python-lolcat
             : and much faster than ruby-lolcat. It works well with "non-binary"
             : characters, but who would want to display binary data!
```

The package is built from [the release tagged v1.0](https://github.com/jaseg/lolcat/releases/tag/v1.0).

**Comment by trk9001** [comment]
## Update

I built lolcat from [the latest commit](https://github.com/jaseg/lolcat/commit/5b97d040b303a8e4761ed76661ab880fbcd099fb) and the issue is still present, with a slight change: it now says `Error reading input file "...": Success` and moreover this error message is colored. Screenshot below:

![lolcat-latest-error](https://user-images.githubusercontent.com/32555337/102922076-a43b8480-44b7-11eb-91c2-f32c06ca00a6.jpg)

**Comment by jaseg** [comment]
Good catch! This is because lolcat uses fclose incorrectly, cf. https://bugzilla.redhat.com/show_bug.cgi?id=21216

**Comment by jaseg** [comment]
Thank you for the report. This issue should be fixed in master. Please validate the fix. I will then prepare a minor release.

**Comment by trk9001** [comment]
The fix worked—the issue is no longer present in the binary built from [master](https://github.com/jaseg/lolcat/tree/a1dfac8cf45decc99d1a0f6f86a52f65baf96506). Please go ahead with the release as you see fit. And thank you for your swift response.
