### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by XenGi** [jaseg/lolcat#4]
```
$ lolcat --help
fish: “lolcat --help” terminated by signal SIGSEGV (Address boundary error)
$ lolcat -h
Usage: lolcat [-h horizontal_speed] [-v vertical_speed] [--] [FILES...]
```

would be nice if --help also works or at least doesn't segfault. ;)

**Comment by jaseg** [comment]
lol, will fix later today^^

**Comment by jaseg** [comment]
hmm, just compile with ```make lolcat-static``` and ```mv lolcat-static lolcat```. I vaguely remember that there is an open bug in glibc's fmemopen for ages now. Using the musl that comes with lolcat-static everything works.
