### ISSUE TITLE
OMG! Now we need Perlin noise!

### ISSUE THREAD

**Issue by daniel-santos** [jaseg/lolcat#41]
This is a time sink, but an awesome one!  Maybe I can look at the animated mode too.  I need to experiment more with this.  There's SO many stupid possibilities!

[Perlin Noise](https://en.wikipedia.org/wiki/Perlin_noise) on Wikipedia.

**Comment by mazznoer** [comment]
@daniel-santos you can use [lolcrab](https://github.com/mazznoer/lolcrab)

**Comment by jaseg** [comment]
That is an amazing tool! I think it's ok if this lolcat here is a simple beginner's lolcat, and I think its good that there are more advanced lolcats for more sophisticated lolcat users ^^
