### ISSUE TITLE
Images and lolcat

### ISSUE THREAD

**Issue by PROxZIMA** [jaseg/lolcat#42]
![Screenshot from 2021-11-29 08-31-10](https://user-images.githubusercontent.com/43103163/143804152-461a054a-42d1-4d4f-83fb-c03aa75d2a94.png)

```bash
$ lolcat --version
lolcat version 1.2, (c) 2020 jaseg

$ kitty -v
kitty 0.23.1 created by Kovid Goyal

$ neofetch -v
Neofetch version: 7.1.0
```
- Neofetch `image_backend="kitty"`

As you can see using lolcat while rendering image isn't working.
Any workaround available?

**Comment by jaseg** [comment]
Ouch! Uhm....  that needs some tuning of the escape sequence parser. Right now it swallows all escape sequences, but its grammar only covers the common color/font escapes. Do you have a link to some documentation describing the protocol neofetch is using there? Is it [this one described in the Kitty doc](https://sw.kovidgoyal.net/kitty/graphics-protocol/) or are there multiple such graphics protocols?

**Comment by PROxZIMA** [comment]
From `neofetch` source code:

https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L4475-L4480

It uses Kitty's graphics protocol, which you linked above.

**Comment by jaseg** [comment]
I extended the escape sequence parser in a way that I hope should catch most terminal graphics protocols. Please check it out and tell me if it works for you.
