### ISSUE TITLE
Add option to use just base 16 colors of terminal

### ISSUE THREAD

**Issue by poetaman** [jaseg/lolcat#43]
Add option to use just base 16 colors of terminal, thanks!

**Comment by scarf** [comment]
Just change [lolcat.c#L60](https://github.com/jaseg/lolcat/blob/main/lolcat.c#L60) to:
`const unsigned char codes[] = { 1, 3, 2, 6, 4, 5, 13, 12, 14, 10, 11, 9  };`
(or whatever colors/order you want to use) and recompile it as `lolcat-16`?

![image](https://user-images.githubusercontent.com/2446600/202847038-7a19f1ba-1d9d-4fce-8d47-5168afa23867.png)

**Comment by jaseg** [comment]
That might not work in all terminals, since that will still produce the \e[38;5;xxxm 256-color escape sequences. So it will use the 16 ANSI colors on a 256-color-enabled terminal, but might not work in places that don't have 256 color support in the first place.

**Comment by scarf** [comment]
I see you liked my order of the colors, at least 😉
