### ISSUE TITLE
(Suggestion) Gradient support?

### ISSUE THREAD

**Issue by user-420** [jaseg/lolcat#47]
Rather than a rainbow, have a mode that takes x amount of colors and makes a nice gradient between them.

ex:
lolcat --c1 ff0000 --c2 0000ff
would make a gradient from red -> blue
if --c1/c2/etc args are not provided, just use a rainbow as normal

**Comment by scarf** [comment]
How about https://github.com/armanirodriguez/ansifade ?

**Comment by jaseg** [comment]
> How about https://github.com/armanirodriguez/ansifade ?

That does not handle wide characters properly, nor does it process incoming escape sequences at all. This will lead to corrupted output when there are escape sequences in the input.

**Comment by jaseg** [comment]
I think this is a neat idea, and I added it to lolcat. Thanks!

**Comment by user-420** [comment]
Thanks for adding it
