### ISSUE TITLE
[voidlinux] Extra characters when using lolcat-c with neofetch

### ISSUE THREAD

**Issue by SpidFightFR** [jaseg/lolcat#48]
Hello everyone, i got this issue with lolcat and neofetch [some extra-characters](https://media.discordapp.net/attachments/1075092296351105107/1075092296871186452/image.png) appear in the output. 

It doesn't happen with regular neofetch, and it doesn't happen with lolcat when using another input command (like cat).
I suspect it's linked to a font change in neofetch, either color or something else...

Thanks for the help, by advance.

**Comment by jaseg** [comment]
That's broken terminal escape sequences. Can you pipe neofetch like you use it in that screenshot into a file and post that file here? Perhaps lolcat's escape sequence parsing is broken.

As a workaround, you could tell neofetch not to emit its own color escapes if neofetch has something like a `--color` option (I'm not familiar with it).

**Comment by SpidFightFR** [comment]
wait actually it displays something wierd with a gui editor... So here's the file [with lolcat](https://github.com/jaseg/lolcat/files/10807107/with_lolcat.txt), if you wish

**Comment by SpidFightFR** [comment]
According to my observations, the issue started happening since version 1.3 of lolcat. Can it help?

**Comment by jaseg** [comment]
Fixed in v1.4. The issue was that neofetch sometimes puts several escape sequences right after one another, and that confused the minimalist escape sequence parser in lolcat.

**Comment by jaseg** [comment]
Thank you for the report!

**Comment by SpidFightFR** [comment]
Wow! You’re very efficient! Nicely done mate! I’ll try to make a pr for void!

**Comment by SpidFightFR** [comment]
Thank you for solving this fast!
