### ISSUE TITLE
Makefile uses DESTDIR incorrectly

### ISSUE THREAD

**Issue by ryandesign** [jaseg/lolcat#56]
https://github.com/jaseg/lolcat/blob/f2c26ed7a72828f94f174ab8c84676856fbe2097/Makefile#L6

https://github.com/jaseg/lolcat/blob/f2c26ed7a72828f94f174ab8c84676856fbe2097/Makefile#L24-L26

This is not what other projects use DESTDIR for.

Instead, you should use:

```make
prefix ?= /usr/local
...
install: lolcat censor
 	install lolcat $(DESTDIR)$(prefix)/bin 
 	install censor $(DESTDIR)$(prefix)/bin
```

DESTDIR will normally be empty but package management systems may set it to a temporary staging directory in which files will be collected before being moved to the final location.

**Comment by jaseg** [comment]
I think I used that name by accident, I'll fix it on main.
