### ISSUE TITLE
Makefile deficiencies

### ISSUE THREAD

**Issue by ryandesign** [jaseg/lolcat#57]
https://github.com/jaseg/lolcat/blob/f2c26ed7a72828f94f174ab8c84676856fbe2097/Makefile#L18-L22

You also need to use $(CPPFLAGS) when compiling.

You also need touse $(LDFLAGS) when linking.

You should not compile and link in a single step. Do it in separate steps.

You should not need to repeat the compile commands in multiple rules. There should be a global rule that knows how to compile any .c file into a .o file. There is even a default rule that probably already does the right thing.

**Comment by jaseg** [comment]
I've added CPPFLAGS and LDFLAGS for people that need it. Your other points I agree with in principle, but this is a Makefile compiling a single 475-line C file to a 25kB executable, so I prefer to keep things as simple as possible. Users who don't like the provided makefile can easily supply their own compiler invocation.

**Comment by jaseg** [comment]
Thank you for the issue!
