### ISSUE TITLE
README references images on master branch

### ISSUE THREAD

**Issue by ryandesign** [jaseg/lolcat#59]
The README pulls images from the master branch:

https://github.com/jaseg/lolcat/blob/f2c26ed7a72828f94f174ab8c84676856fbe2097/README.md?plain=1#L1-L9

but you haven't updated the master branch in three years; development is now on the main branch. How about changing the references in the README to the main branch and deleting the master branch, to reduce confusion?

Do the images need to pull from absolute URLs? The third image, sl.gif, is referenced by relative path; could that be used for the other images as well?

**Comment by jaseg** [comment]
I made that README 10 years ago, and IIRC github back then had some issues embedding images in READMEs. I'll have a look at fixing it.
