### ISSUE TITLE
OmniOS/Illumos build failure related to sys/time.h

### ISSUE THREAD

**Issue by andrewhotlab** [jaseg/lolcat#61]
Hi, I'd like to use lolcat in OmniOS, so I'm trying to build it, but I get this error:

```
# gmake
gcc  -std=c11 -Wall -Wextra -O3 -Wno-sign-compare  -o lolcat lolcat.c -lm
lolcat.c: In function 'main':
lolcat.c:215:20: error: storage size of 'tv' isn't known
  215 |     struct timeval tv;
      |                    ^~
lolcat.c:216:5: error: implicit declaration of function 'gettimeofday' [-Wimplicit-function-declaration]
  216 |     gettimeofday(&tv, NULL);
      |     ^~~~~~~~~~~~
lolcat.c:215:20: warning: unused variable 'tv' [-Wunused-variable]
  215 |     struct timeval tv;
      |                    ^~
gmake: *** [Makefile:19: lolcat] Error 1
```

I'm not a developer thus it may sound a stupid question... someone can suggest how can I solve the issue?

**Comment by jaseg** [comment]
I don't have an illumos ready to debug this, but from what this looks like it seems like they might deviate from posix here. According to posix, `sys/time.h`, which is included in `lolcat.c` should define both `struct timeval` and `gettimeofday`: https://pubs.opengroup.org/onlinepubs/007904975/basedefs/sys/time.h.html

If someone with illumos wants to chime in, I'm all ears. I'll merge any MR that fixes this without breaking builds on other OSes.

**Comment by richlowe** [comment]
The problem (from the illumos POV, at least) is that you defined `_XOPEN_SOURCE` with no value at the top of `lolcat.c`, which requests the XPG3 standards (pre posix, X/Open).  Without that everything is fine.

Requesting XPG3 in combination with C11 is definitely off, because C11 requires XPG6.
I'm not sure _specifically_ how this falls through the mass of backward-compatibility and standards-namespace-compatibility ifdefs to fail though, just that that is why it is failing.

You probably want

`#define _XOPEN_SOURCE 600` for at least xpg6?, or `POSIX_C_SOURCE 200112L`

The other values are in illumos `sys/feature_tests.h` and have standard meanings, the table in the header says

```c
 * When writing a conforming X/Open application, as per the specification                                                                                    
 * requirements, the appropriate feature test macros must be defined at                                                                                      
 * compile time. These are as follows. For more info, see standards(7).                                                                                      
 *                                                                                                                                                           
 * Feature Test Macro                                Specification                                                                                           
 * ------------------------------------------------  -------------                                                                                           
 * _XOPEN_SOURCE                                         XPG3                                                                                                
 * _XOPEN_SOURCE && _XOPEN_VERSION = 4                   XPG4                                                                                                
 * _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED = 1           XPG4v2                                                                                              
 * _XOPEN_SOURCE = 500                                   XPG5                                                                                                
 * _XOPEN_SOURCE = 600  (or POSIX_C_SOURCE=200112L)      XPG6                                                                                                
 * _XOPEN_SOURCE = 700  (or POSIX_C_SOURCE=200809L)      XPG7                                                                                                
 * _XOPEN_SOURCE = 800  (or POSIX_C_SOURCE=202405L)      XPG8                                                                                                
 *                                   
```

I included the top comment only because of the reference to https://illumos.org/man/7/standards which maybe says this better than I am.

**Comment by jaseg** [comment]
Thank you for the information. I've merged OP's MR, and I think this issue should be fixed now. Please feel free to comment or re-open if it didn't fix it.
