### ISSUE TITLE
Document `censor`

### ISSUE THREAD

**Issue by Property404** [jaseg/lolcat#62]
I see this repo includes the `censor` tool, but I don't see any documentation of what it does or how to use it. Maybe include it in the README, or have a `--help` flag?

(I really have no idea what this tool is or what it's used for)

**Comment by jaseg** [comment]
Try it out, it doesn't do anything nefarious ;)

**Comment by Property404** [comment]
I have tried it, but I don't understand. It just makes texts into blocks?

**Comment by jaseg** [comment]
yeah, it's just a toy :)
