### ISSUE TITLE
AUR package out of date

### ISSUE THREAD

**Issue by n-a-m-e** [jaseg/lolcat#8]
just tried installing latest version with yaourt and I am getting the following errors:
without musl installed:

<pre><code>"musl not found. If the build does not go through, consider either installing"
"musl system-wide using your favorite package manager or fetching and building a"
"local copy using:"
"git submodule init"
"git submodule update"
"make musl"
"Using musl at "
cd musl; ./configure
/bin/sh: ./configure: No such file or directory
make: *** [Makefile.musl:24: musl/config.mak] Error 127</code></pre>

with musl installed:
<pre><code>"Using musl at /usr/lib/musl"
cd musl; ./configure
/bin/sh: ./configure: No such file or directory
make: *** [Makefile.musl:24: musl/config.mak] Error 127</code></pre>

**Comment by jaseg** [comment]
Try again. The make targets were in the wrong order.

**Comment by n-a-m-e** [comment]
Build still fails without musl installed.

adding makedepends=('musl') to the PKGBUILD fixes everything.

**Comment by jaseg** [comment]
In what way does it fail? Could you paste the make output here? Also, could you make *really* sure you're running the build from a clean repo state?

Thank you, and sorry for the trouble!

**Comment by n-a-m-e** [comment]
I uninstalled both c-lolcat and musl then ran the following command
<pre><code>yaourt c-lolcat | tee lolcat.log</pre></code>
the following was in the log file:
<pre><code>1 aur/c-lolcat r27.33ee440-2 (0) (0.00)
    High-performance implementation of lolcat

c-lolcat r27.33ee440-2  (2016-10-27 09:02)
( Unsupported package: Potentially dangerous ! )

"musl not found. If the build does not go through, consider either installing"
"musl system-wide using your favorite package manager or fetching and building a"
"local copy using:"
"git submodule init"
"git submodule update"
"make musl"
"Using musl at "
gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -I/include -o lolcat.o lolcat.c
gcc -s -nostartfiles -nodefaultlibs -nostdinc -static -ffunction-sections -fdata-sections -Wl,--gc-sections -o lolcat-static lolcat.o /lib/crt1.o /lib/libc.a</pre></code>
This is what was printed in the terminal:
<pre><code>1 aur/c-lolcat r27.33ee440-2 (0) (0.00)
    High-performance implementation of lolcat
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> 1


==> Downloading c-lolcat PKGBUILD from AUR...
x .SRCINFO
x .gitignore
x PKGBUILD
c-lolcat r27.33ee440-2  (2016-10-27 09:02)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> c-lolcat dependencies:


==> Continue building c-lolcat ? [Y/n]
==> ----------------------------------
==> y

==> Building and installing package
==> Making package: c-lolcat r27.33ee440-2 (Mon Nov 21 13:48:58 AEDT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning c-lolcat git repo...
Cloning into bare repository '/tmp/yaourt-tmp-username/aur-c-lolcat/c-lolcat'...
remote: Counting objects: 140, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 140 (delta 12), reused 0 (delta 0), pack-reused 115
Receiving objects: 100% (140/140), 1.69 MiB | 348.00 KiB/s, done.
Resolving deltas: 100% (69/69), done.
==> Validating source files with sha256sums...
    c-lolcat ... Skipped
==> Extracting sources...
  -> Creating working copy of lolcat git repo...
Cloning into 'c-lolcat'...
done.
==> Starting pkgver()...
==> Updated version: c-lolcat r34.8e95919-1
==> Starting build()...
"musl not found. If the build does not go through, consider either installing"
"musl system-wide using your favorite package manager or fetching and building a"
"local copy using:"
"git submodule init"
"git submodule update"
"make musl"
"Using musl at "
gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -I/include -o lolcat.o lolcat.c
lolcat.c: In function ‘main’:
lolcat.c:153:70: warning: implicit declaration of function ‘wcwidth’ [-Wimplicit-function-declaration]
                        int ncc = offx*ARRAY_SIZE(codes) + (int)((i+=wcwidth(c))*freq_h + l*freq_v);
                                                                     ^~~~~~~
gcc -s -nostartfiles -nodefaultlibs -nostdinc -static -ffunction-sections -fdata-sections -Wl,--gc-sections -o lolcat-static lolcat.o /lib/crt1.o /lib/libc.a
/lib/libc.a(elf-init.o): In function `__libc_csu_init':
(.text+0x5c): undefined reference to `_init'
/lib/libc.a(elf-init.o): In function `__libc_csu_fini':
(.text+0xbf): undefined reference to `_fini'
/lib/libc.a(iofclose.o): In function `_IO_new_fclose':
(.text+0x288): undefined reference to `_Unwind_Resume'
/lib/libc.a(iofclose.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(iofflush.o): In function `_IO_fflush':
(.text+0x173): undefined reference to `_Unwind_Resume'
/lib/libc.a(iofflush.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(ioputs.o): In function `_IO_puts':
(.text+0x20c): undefined reference to `_Unwind_Resume'
/lib/libc.a(ioputs.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(getwc.o): In function `_IO_getwc':
(.text+0x12a): undefined reference to `_Unwind_Resume'
/lib/libc.a(getwc.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(wfileops.o): In function `_IO_wfile_underflow':
(.text+0x724): undefined reference to `_Unwind_Resume'
/lib/libc.a(wfileops.o):(.eh_frame+0x6b): undefined reference to `__gcc_personality_v0'
/lib/libc.a(fileops.o): In function `_IO_new_file_underflow':
(.text+0x5ef): undefined reference to `_Unwind_Resume'
/lib/libc.a(fileops.o):(.eh_frame+0xe7): undefined reference to `__gcc_personality_v0'
/lib/libc.a(backtrace.o): In function `backtrace_helper':
(.text+0x24): undefined reference to `_Unwind_GetIP'
/lib/libc.a(backtrace.o): In function `backtrace_helper':
(.text+0x30): undefined reference to `_Unwind_GetCFA'
/lib/libc.a(backtrace.o): In function `__backtrace':
(.text+0xbc): undefined reference to `_Unwind_Backtrace'
/lib/libc.a(iofputs.o): In function `_IO_fputs':
(.text+0x188): undefined reference to `_Unwind_Resume'
/lib/libc.a(iofputs.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(iofwrite.o): In function `_IO_fwrite':
(.text+0x20d): undefined reference to `_Unwind_Resume'
/lib/libc.a(iofwrite.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(iogetdelim.o): In function `_IO_getdelim':
(.text+0x328): undefined reference to `_Unwind_Resume'
/lib/libc.a(iogetdelim.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(fseek.o): In function `fseek':
(.text+0x11d): undefined reference to `_Unwind_Resume'
/lib/libc.a(fseek.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(ftello.o): In function `__ftello':
(.text+0x192): undefined reference to `_Unwind_Resume'
/lib/libc.a(ftello.o):(.eh_frame+0x13): undefined reference to `__gcc_personality_v0'
/lib/libc.a(ioseekoff.o): In function `_IO_seekoff':
(.text+0x251): undefined reference to `_Unwind_Resume'
/lib/libc.a(ioseekoff.o):(.eh_frame+0x67): undefined reference to `__gcc_personality_v0'
collect2: error: ld returned 1 exit status
make: *** [Makefile:24: lolcat-static] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build c-lolcat.
==> Restart building c-lolcat ? [y/N]
==> ---------------------------------
==> n</pre></code>

**Comment by jaseg** [comment]
Ok, yeah. I'll have to poke the guy doing the AUR package, that one is just not up-to-date as the musl dependency is missing. It will work (I think) if you build it from the PKGBUILD in this here source tree.

**Comment by n-a-m-e** [comment]
Yeah building with the PKGBUILD from here works, so it's just the AUR package that's out of date.

**Comment by n-a-m-e** [comment]
Everything is installing fine now. it's just throwing this error https://github.com/jaseg/lolcat/issues/9, so I'll close this issue.
